apiVersion: v1
kind: Pod
metadata:
  name: test-django-pod
spec:
  containers:
  - name: container-nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: container-testdjango
    image: python:3.8.3-alpine
    ports:
    - containerPort: 8080
    #command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]